# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(839, 554)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.gridLayout = QtWidgets.QGridLayout(self.main_page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.main_menu_mps = QtWidgets.QPushButton(self.main_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_menu_mps.sizePolicy().hasHeightForWidth())
        self.main_menu_mps.setSizePolicy(sizePolicy)
        self.main_menu_mps.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.main_menu_mps.setFont(font)
        self.main_menu_mps.setObjectName("main_menu_mps")
        self.horizontalLayout.addWidget(self.main_menu_mps)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.main_menu_mes = QtWidgets.QPushButton(self.main_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_menu_mes.sizePolicy().hasHeightForWidth())
        self.main_menu_mes.setSizePolicy(sizePolicy)
        self.main_menu_mes.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.main_menu_mes.setFont(font)
        self.main_menu_mes.setObjectName("main_menu_mes")
        self.horizontalLayout.addWidget(self.main_menu_mes)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.main_menu_admin = QtWidgets.QPushButton(self.main_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_menu_admin.sizePolicy().hasHeightForWidth())
        self.main_menu_admin.setSizePolicy(sizePolicy)
        self.main_menu_admin.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.main_menu_admin.setFont(font)
        self.main_menu_admin.setObjectName("main_menu_admin")
        self.horizontalLayout.addWidget(self.main_menu_admin)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.main_heading = QtWidgets.QLabel(self.main_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.main_heading.setFont(font)
        self.main_heading.setTextFormat(QtCore.Qt.PlainText)
        self.main_heading.setScaledContents(False)
        self.main_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.main_heading.setObjectName("main_heading")
        self.gridLayout.addWidget(self.main_heading, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.main_page)
        self.mps_page = QtWidgets.QWidget()
        self.mps_page.setObjectName("mps_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.mps_page)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line = QtWidgets.QFrame(self.mps_page)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 2, 0, 1, 2)
        self.mps_display_support = QtWidgets.QTableWidget(self.mps_page)
        self.mps_display_support.setMinimumSize(QtCore.QSize(256, 0))
        self.mps_display_support.setGridStyle(QtCore.Qt.SolidLine)
        self.mps_display_support.setRowCount(8)
        self.mps_display_support.setColumnCount(17)
        self.mps_display_support.setObjectName("mps_display_support")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mps_display_support.setHorizontalHeaderItem(16, item)
        self.mps_display_support.horizontalHeader().setVisible(False)
        self.mps_display_support.horizontalHeader().setCascadingSectionResizes(True)
        self.mps_display_support.horizontalHeader().setDefaultSectionSize(120)
        self.mps_display_support.horizontalHeader().setMinimumSectionSize(31)
        self.mps_display_support.horizontalHeader().setSortIndicatorShown(True)
        self.mps_display_support.horizontalHeader().setStretchLastSection(True)
        self.mps_display_support.verticalHeader().setVisible(False)
        self.mps_display_support.verticalHeader().setDefaultSectionSize(30)
        self.mps_display_support.verticalHeader().setMinimumSectionSize(24)
        self.gridLayout_4.addWidget(self.mps_display_support, 9, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.mps_page)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 7, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.create_new = QtWidgets.QPushButton(self.mps_page)
        self.create_new.setObjectName("create_new")
        self.horizontalLayout_3.addWidget(self.create_new)
        self.pushButton_2 = QtWidgets.QPushButton(self.mps_page)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.mps_page)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 4, 0, 1, 2)
        self.mps_heading = QtWidgets.QLabel(self.mps_page)
        self.mps_heading.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mps_heading.setFont(font)
        self.mps_heading.setTextFormat(QtCore.Qt.PlainText)
        self.mps_heading.setScaledContents(False)
        self.mps_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.mps_heading.setObjectName("mps_heading")
        self.gridLayout_4.addWidget(self.mps_heading, 1, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mps_sub_page = QtWidgets.QStackedWidget(self.mps_page)
        self.mps_sub_page.setObjectName("mps_sub_page")
        self.mps_sub_page_add = QtWidgets.QWidget()
        self.mps_sub_page_add.setObjectName("mps_sub_page_add")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.mps_sub_page_add)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.create_new_layout = QtWidgets.QGridLayout()
        self.create_new_layout.setObjectName("create_new_layout")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem6)
        self.mps_create_button = QtWidgets.QPushButton(self.mps_sub_page_add)
        self.mps_create_button.setObjectName("mps_create_button")
        self.horizontalLayout_26.addWidget(self.mps_create_button)
        self.mps_cancel_button = QtWidgets.QPushButton(self.mps_sub_page_add)
        self.mps_cancel_button.setObjectName("mps_cancel_button")
        self.horizontalLayout_26.addWidget(self.mps_cancel_button)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem7)
        self.create_new_layout.addLayout(self.horizontalLayout_26, 1, 0, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem8)
        self.label_26 = QtWidgets.QLabel(self.mps_sub_page_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_27.addWidget(self.label_26)
        self.mps_unit_line_edit = QtWidgets.QLineEdit(self.mps_sub_page_add)
        self.mps_unit_line_edit.setObjectName("mps_unit_line_edit")
        self.horizontalLayout_27.addWidget(self.mps_unit_line_edit)
        self.label_27 = QtWidgets.QLabel(self.mps_sub_page_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_27.addWidget(self.label_27)
        self.mps_area_line_edit = QtWidgets.QLineEdit(self.mps_sub_page_add)
        self.mps_area_line_edit.setObjectName("mps_area_line_edit")
        self.horizontalLayout_27.addWidget(self.mps_area_line_edit)
        self.label = QtWidgets.QLabel(self.mps_sub_page_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_27.addWidget(self.label)
        self.mps_cwp_line_edit = QtWidgets.QLineEdit(self.mps_sub_page_add)
        self.mps_cwp_line_edit.setObjectName("mps_cwp_line_edit")
        self.horizontalLayout_27.addWidget(self.mps_cwp_line_edit)
        self.label_28 = QtWidgets.QLabel(self.mps_sub_page_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_27.addWidget(self.label_28)
        self.mps_desc_line_edit = QtWidgets.QLineEdit(self.mps_sub_page_add)
        self.mps_desc_line_edit.setObjectName("mps_desc_line_edit")
        self.horizontalLayout_27.addWidget(self.mps_desc_line_edit)
        self.label_29 = QtWidgets.QLabel(self.mps_sub_page_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_27.addWidget(self.label_29)
        self.mps_openfile_button = QtWidgets.QPushButton(self.mps_sub_page_add)
        self.mps_openfile_button.setObjectName("mps_openfile_button")
        self.horizontalLayout_27.addWidget(self.mps_openfile_button)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem9)
        self.create_new_layout.addLayout(self.horizontalLayout_27, 0, 0, 1, 1)
        self.horizontalLayout_8.addLayout(self.create_new_layout)
        self.mps_sub_page.addWidget(self.mps_sub_page_add)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.mps_sub_page.addWidget(self.page_2)
        self.horizontalLayout_4.addWidget(self.mps_sub_page)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 5, 1, 1, 1)
        self.mps_heading_2 = QtWidgets.QLabel(self.mps_page)
        self.mps_heading_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.mps_heading_2.setFont(font)
        self.mps_heading_2.setTextFormat(QtCore.Qt.PlainText)
        self.mps_heading_2.setScaledContents(False)
        self.mps_heading_2.setAlignment(QtCore.Qt.AlignCenter)
        self.mps_heading_2.setObjectName("mps_heading_2")
        self.gridLayout_4.addWidget(self.mps_heading_2, 0, 0, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(17, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 6, 0, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.mps_btn_refresh = QtWidgets.QPushButton(self.mps_page)
        self.mps_btn_refresh.setObjectName("mps_btn_refresh")
        self.horizontalLayout_25.addWidget(self.mps_btn_refresh)
        self.pushButton = QtWidgets.QPushButton(self.mps_page)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_25.addWidget(self.pushButton)
        self.mps_modify_button = QtWidgets.QPushButton(self.mps_page)
        self.mps_modify_button.setObjectName("mps_modify_button")
        self.horizontalLayout_25.addWidget(self.mps_modify_button)
        spacerItem11 = QtWidgets.QSpacerItem(750, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem11)
        self.gridLayout_4.addLayout(self.horizontalLayout_25, 8, 0, 1, 2)
        spacerItem12 = QtWidgets.QSpacerItem(17, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem12, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.mps_page)
        self.mes_page = QtWidgets.QWidget()
        self.mes_page.setObjectName("mes_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mes_page)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mes_display_support = QtWidgets.QTableWidget(self.mes_page)
        self.mes_display_support.setMinimumSize(QtCore.QSize(256, 0))
        self.mes_display_support.setGridStyle(QtCore.Qt.SolidLine)
        self.mes_display_support.setRowCount(8)
        self.mes_display_support.setColumnCount(17)
        self.mes_display_support.setObjectName("mes_display_support")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mes_display_support.setHorizontalHeaderItem(16, item)
        self.mes_display_support.horizontalHeader().setVisible(False)
        self.mes_display_support.horizontalHeader().setCascadingSectionResizes(True)
        self.mes_display_support.horizontalHeader().setDefaultSectionSize(120)
        self.mes_display_support.horizontalHeader().setMinimumSectionSize(31)
        self.mes_display_support.horizontalHeader().setSortIndicatorShown(True)
        self.mes_display_support.horizontalHeader().setStretchLastSection(True)
        self.mes_display_support.verticalHeader().setVisible(False)
        self.mes_display_support.verticalHeader().setDefaultSectionSize(30)
        self.mes_display_support.verticalHeader().setMinimumSectionSize(24)
        self.gridLayout_3.addWidget(self.mes_display_support, 8, 1, 1, 3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.mes_create_button = QtWidgets.QPushButton(self.mes_page)
        self.mes_create_button.setObjectName("mes_create_button")
        self.horizontalLayout_5.addWidget(self.mes_create_button)
        self.mes_clear_button = QtWidgets.QPushButton(self.mes_page)
        self.mes_clear_button.setObjectName("mes_clear_button")
        self.horizontalLayout_5.addWidget(self.mes_clear_button)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 2, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.label_30 = QtWidgets.QLabel(self.mes_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_6.addWidget(self.label_30)
        self.mes_unit_line_edit = QtWidgets.QLineEdit(self.mes_page)
        self.mes_unit_line_edit.setObjectName("mes_unit_line_edit")
        self.horizontalLayout_6.addWidget(self.mes_unit_line_edit)
        self.label_31 = QtWidgets.QLabel(self.mes_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_6.addWidget(self.label_31)
        self.mes_area_line_edit = QtWidgets.QLineEdit(self.mes_page)
        self.mes_area_line_edit.setObjectName("mes_area_line_edit")
        self.horizontalLayout_6.addWidget(self.mes_area_line_edit)
        self.label_7 = QtWidgets.QLabel(self.mes_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.mes_cwp_line_edit = QtWidgets.QLineEdit(self.mes_page)
        self.mes_cwp_line_edit.setObjectName("mes_cwp_line_edit")
        self.horizontalLayout_6.addWidget(self.mes_cwp_line_edit)
        self.label_33 = QtWidgets.QLabel(self.mes_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_6.addWidget(self.label_33)
        self.mes_desc_line_edit = QtWidgets.QLineEdit(self.mes_page)
        self.mes_desc_line_edit.setObjectName("mes_desc_line_edit")
        self.horizontalLayout_6.addWidget(self.mes_desc_line_edit)
        self.label_32 = QtWidgets.QLabel(self.mes_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_6.addWidget(self.label_32)
        self.mes_openfile_button = QtWidgets.QPushButton(self.mes_page)
        self.mes_openfile_button.setObjectName("mes_openfile_button")
        self.horizontalLayout_6.addWidget(self.mes_openfile_button)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 1, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.mes_btn_refresh = QtWidgets.QPushButton(self.mes_page)
        self.mes_btn_refresh.setObjectName("mes_btn_refresh")
        self.horizontalLayout_7.addWidget(self.mes_btn_refresh)
        self.mes_modify_button = QtWidgets.QPushButton(self.mes_page)
        self.mes_modify_button.setObjectName("mes_modify_button")
        self.horizontalLayout_7.addWidget(self.mes_modify_button)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 5, 2, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.mes_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_9.sizePolicy().hasHeightForWidth())
        self.line_9.setSizePolicy(sizePolicy)
        self.line_9.setMinimumSize(QtCore.QSize(0, 10))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_3.addWidget(self.line_9, 3, 2, 1, 1)
        self.mes_heading = QtWidgets.QLabel(self.mes_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mes_heading.setFont(font)
        self.mes_heading.setTextFormat(QtCore.Qt.PlainText)
        self.mes_heading.setScaledContents(False)
        self.mes_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.mes_heading.setObjectName("mes_heading")
        self.gridLayout_3.addWidget(self.mes_heading, 0, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem18, 4, 2, 1, 1)
        self.stackedWidget.addWidget(self.mes_page)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuModules = QtWidgets.QMenu(self.menubar)
        self.menuModules.setObjectName("menuModules")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionAdd_New = QtWidgets.QAction(mainWindow)
        self.actionAdd_New.setObjectName("actionAdd_New")
        self.actionClose = QtWidgets.QAction(mainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionCopy = QtWidgets.QAction(mainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(mainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionMPS_Misc_Pipe_Supports = QtWidgets.QAction(mainWindow)
        self.actionMPS_Misc_Pipe_Supports.setObjectName("actionMPS_Misc_Pipe_Supports")
        self.actionMES_Misc_Electrical_Supports = QtWidgets.QAction(mainWindow)
        self.actionMES_Misc_Electrical_Supports.setObjectName("actionMES_Misc_Electrical_Supports")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAdmin = QtWidgets.QAction(mainWindow)
        self.actionAdmin.setObjectName("actionAdmin")
        self.actionAdmin_2 = QtWidgets.QAction(mainWindow)
        self.actionAdmin_2.setObjectName("actionAdmin_2")
        self.menuFile.addAction(self.actionAdd_New)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuModules.addAction(self.actionMPS_Misc_Pipe_Supports)
        self.menuModules.addAction(self.actionMES_Misc_Electrical_Supports)
        self.menuModules.addSeparator()
        self.menuModules.addAction(self.actionAdmin_2)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuModules.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(mainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.mps_sub_page.setCurrentIndex(0)
        self.actionClose.triggered.connect(mainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Miscellaneous Support Management"))
        self.main_menu_mps.setText(_translate("mainWindow", "\n"
"MPS \n"
" Misc. Pipe Supports\n"
""))
        self.main_menu_mes.setText(_translate("mainWindow", "\n"
"MES\n"
"Misc. Electrical Supports\n"
""))
        self.main_menu_admin.setText(_translate("mainWindow", "\n"
"Project\n"
"Administration\n"
""))
        self.main_heading.setText(_translate("mainWindow", "MISCELLANEOUS SUPPORT MANAGEMENT"))
        item = self.mps_display_support.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "SuppNo"))
        item = self.mps_display_support.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Unit"))
        item = self.mps_display_support.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Area"))
        item = self.mps_display_support.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "CWP No."))
        item = self.mps_display_support.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Description"))
        item = self.mps_display_support.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "SuppStatus"))
        item = self.mps_display_support.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "Requested By"))
        item = self.mps_display_support.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "Requested Date"))
        item = self.mps_display_support.horizontalHeaderItem(8)
        item.setText(_translate("mainWindow", "Modified By"))
        item = self.mps_display_support.horizontalHeaderItem(9)
        item.setText(_translate("mainWindow", "Modified Date"))
        item = self.mps_display_support.horizontalHeaderItem(10)
        item.setText(_translate("mainWindow", "Implemented By"))
        item = self.mps_display_support.horizontalHeaderItem(11)
        item.setText(_translate("mainWindow", "Implemented Date"))
        item = self.mps_display_support.horizontalHeaderItem(12)
        item.setText(_translate("mainWindow", "Approved By"))
        item = self.mps_display_support.horizontalHeaderItem(13)
        item.setText(_translate("mainWindow", "Approved Date"))
        item = self.mps_display_support.horizontalHeaderItem(14)
        item.setText(_translate("mainWindow", "Rejected By"))
        item = self.mps_display_support.horizontalHeaderItem(15)
        item.setText(_translate("mainWindow", "Rejected Date"))
        item = self.mps_display_support.horizontalHeaderItem(16)
        item.setText(_translate("mainWindow", "Rejection Reason"))
        self.create_new.setText(_translate("mainWindow", "New"))
        self.pushButton_2.setText(_translate("mainWindow", "Modify"))
        self.pushButton_3.setText(_translate("mainWindow", "Change Status"))
        self.mps_heading.setText(_translate("mainWindow", " PIPE SUPPORTS"))
        self.mps_create_button.setText(_translate("mainWindow", "Create"))
        self.mps_cancel_button.setText(_translate("mainWindow", "Cancel"))
        self.label_26.setText(_translate("mainWindow", "Unit"))
        self.label_27.setText(_translate("mainWindow", "Area"))
        self.label.setText(_translate("mainWindow", "CWP No."))
        self.label_28.setText(_translate("mainWindow", "Description"))
        self.label_29.setText(_translate("mainWindow", "SnapShot"))
        self.mps_openfile_button.setText(_translate("mainWindow", "Attach"))
        self.mps_heading_2.setText(_translate("mainWindow", "KNPC AL-ZOUR REFINERY"))
        self.mps_btn_refresh.setText(_translate("mainWindow", "Refresh"))
        self.pushButton.setText(_translate("mainWindow", "Export"))
        self.mps_modify_button.setText(_translate("mainWindow", "View Support"))
        item = self.mes_display_support.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "SuppNo"))
        item = self.mes_display_support.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Unit"))
        item = self.mes_display_support.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Area"))
        item = self.mes_display_support.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "CWP No."))
        item = self.mes_display_support.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Description"))
        item = self.mes_display_support.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "SuppStatus"))
        item = self.mes_display_support.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "Requested By"))
        item = self.mes_display_support.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "Requested Date"))
        item = self.mes_display_support.horizontalHeaderItem(8)
        item.setText(_translate("mainWindow", "Modified By"))
        item = self.mes_display_support.horizontalHeaderItem(9)
        item.setText(_translate("mainWindow", "Modified Date"))
        item = self.mes_display_support.horizontalHeaderItem(10)
        item.setText(_translate("mainWindow", "Implemented By"))
        item = self.mes_display_support.horizontalHeaderItem(11)
        item.setText(_translate("mainWindow", "Implemented Date"))
        item = self.mes_display_support.horizontalHeaderItem(12)
        item.setText(_translate("mainWindow", "Approved By"))
        item = self.mes_display_support.horizontalHeaderItem(13)
        item.setText(_translate("mainWindow", "Approved Date"))
        item = self.mes_display_support.horizontalHeaderItem(14)
        item.setText(_translate("mainWindow", "Rejected By"))
        item = self.mes_display_support.horizontalHeaderItem(15)
        item.setText(_translate("mainWindow", "Rejected Date"))
        item = self.mes_display_support.horizontalHeaderItem(16)
        item.setText(_translate("mainWindow", "Rejection Reason"))
        self.mes_create_button.setText(_translate("mainWindow", "Create"))
        self.mes_clear_button.setText(_translate("mainWindow", "Clear"))
        self.label_30.setText(_translate("mainWindow", "Unit"))
        self.label_31.setText(_translate("mainWindow", "Area"))
        self.label_7.setText(_translate("mainWindow", "CWP No."))
        self.label_33.setText(_translate("mainWindow", "Description"))
        self.label_32.setText(_translate("mainWindow", "SnapShot"))
        self.mes_openfile_button.setText(_translate("mainWindow", "Attach"))
        self.mes_btn_refresh.setText(_translate("mainWindow", "Refresh"))
        self.mes_modify_button.setText(_translate("mainWindow", "Modify"))
        self.mes_heading.setText(_translate("mainWindow", "ELECTRICAL SUPPORTS "))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuEdit.setTitle(_translate("mainWindow", "Edit"))
        self.menuModules.setTitle(_translate("mainWindow", "Modules"))
        self.menuAbout.setTitle(_translate("mainWindow", "About"))
        self.actionAdd_New.setText(_translate("mainWindow", "Add New"))
        self.actionClose.setText(_translate("mainWindow", "Close"))
        self.actionCopy.setText(_translate("mainWindow", "Copy"))
        self.actionPaste.setText(_translate("mainWindow", "Paste"))
        self.actionMPS_Misc_Pipe_Supports.setText(_translate("mainWindow", "MPS - Misc. Pipe Supports"))
        self.actionMES_Misc_Electrical_Supports.setText(_translate("mainWindow", "MES - Misc. Electrical Supports"))
        self.actionAbout.setText(_translate("mainWindow", "About"))
        self.actionAdmin.setText(_translate("mainWindow", "Admin"))
        self.actionAdmin_2.setText(_translate("mainWindow", "Admin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

